version: '3.8'

services:
  flask-app:
    image: python:3.8
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install -r requirements.txt &&
             python flask_app.py"
