name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask App
        run: |
          nohup flask run --host=0.0.0.0 --port=5000 &

      - name: Wait for Flask App to Start
        run: sleep 10

      - name: Run tests
        run: |
          pytest --html=report.html --cov=flask_app --cov-report=html

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: report.html

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: htmlcov
