name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      flask-app:
        image: python:3.8
        ports:
          - 5000:5000
        options: >-
          --health-cmd "curl --fail http://localhost:5000 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Install dependencies
        run: |
          docker-compose exec flask-app sh -c "
          pip install -r requirements.txt"

      - name: Run tests
        run: |
          docker-compose exec flask-app sh -c "
          pytest --html=report.html --cov=flask_app --cov-report=html"

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: report.html

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: htmlcov
